name: Build and Deploy

on:
  push:
    branches:
      - main # ou a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backstage:latest ./backstage/packages/backend/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/backstage:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to Droplet and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 143.244.223.59
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project
            docker-compose down
            docker-compose pull
            docker-compose up -d
