name: Build and Deploy

on:
  push:
    branches:
      - main # ou a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Check out code
        uses: actions/checkout@v3

      # Passo 2: Login no GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Passo 3: Listagem de arquivos para depuração (verifique a estrutura do diretório)
      - name: List files for debugging
        run: |
          ls
          ls -R ./backstage/packages

      # Passo 4: Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backstage:latest -f ./packages/backend/Dockerfile ./packages/backend

      # Passo 5: Push da imagem para o GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/backstage:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to Droplet and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 143.244.223.59
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project
            docker-compose down
            docker-compose pull
            docker-compose up -d
